name: CI

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Writecode@123
          MYSQL_DATABASE: hcsye6225ealth
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: |
          until nc -z localhost 3306; do
            sleep 1
          done
      - name: Debug MySQL Container
        run: docker logs ${{ job.services.mysql.id }}

      - name: Create GitHub Actions MySQL User and Grant Privileges
        run: |
          mysql -h 127.0.0.1 -u root -p6068 -e "CREATE USER 'vidya'@'172.18.0.1' IDENTIFIED BY 'Writecode@123';"
          mysql -h 127.0.0.1 -u root -p6068 -e "GRANT ALL PRIVILEGES ON health.* TO 'vidya'@'172.18.0.1';"
          mysql -h 127.0.0.1 -u root -p6068 -e "FLUSH PRIVILEGES;"
      - name: Run tests
        run: npm test

      - name: Stop MySQL container
        run: docker stop ${{ job.services.mysql.id }}