name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: 'postgres:latest'
        env:
          POSTGRES_DB: 'webapp'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'password'
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.6
        uses: actions/setup-node@v2
        with:
          node-version: 20.6
          cache: 'npm'

      - name: Create .env file
        run: |
          echo PGDATABASE=webapp >> .env
          echo PGUSER=postgres >> .env
          echo PGPASSWORD=password >> .env
          echo PGPORT=5432 >> .env
          echo PGHOST=localhost >> .env
          echo DB_DIALECT=postgres >> .env

      - name: Display .env file
        run: cat .env

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
